import { describe, expect, it } from 'vitest'
import {
  deriveIdentityActions,
  getIdentityActionPhase,
  type IdentityActionContext,
} from '../utils/identityActionLadder'
import {
  deriveIdentityQueue,
  deriveIdentityReadiness,
  type IdentityQueueInput,
} from '../utils/identityNextQueue'
import type { IdentityAttentionItem } from '../utils/identityAttentionQueue'

// A context where every generation step is satisfied → getIdentityActionPhase === 'review'.
const completeContext: IdentityActionContext = {
  bulletDepthCount: 0,
  skillPendingCount: 0,
  hasSkillDepthToReview: true,
  hasPendingSkillDepth: false,
  hasThesis: true,
  hasProfiles: true,
  hasChapters: true,
  canGenerateChapters: true,
  hasSelfKnowledge: true,
  hasPositioning: true,
  hasSearchStrategy: true,
  skillInferenceLabel: 'Review skill depth',
}

const buildInput = (
  context: IdentityActionContext,
  attentionItems: IdentityAttentionItem[] = [],
  staleSections: IdentityQueueInput['staleSections'] = [],
): IdentityQueueInput => ({
  actionItems: deriveIdentityActions(context),
  actionPhase: getIdentityActionPhase(context),
  attentionItems,
  staleSections,
})

const attention = (overrides: Partial<IdentityAttentionItem> = {}): IdentityAttentionItem => ({
  id: 'fill:thesis',
  kind: 'fill-strength',
  title: 'Strengthen identity thesis',
  body: 'Thesis is sparse. Add concrete evidence.',
  statusLabel: 'Sparse',
  layer: 'thesis',
  selection: { type: 'thesis' },
  ...overrides,
})

describe('deriveIdentityQueue', () => {
  it('returns an empty queue when nothing is pending, stale, or needs attention', () => {
    const queue = deriveIdentityQueue(buildInput(completeContext))
    expect(queue).toEqual([])
  })

  it('surfaces the single current ladder step as a non-dismissable next-action', () => {
    const context = { ...completeContext, hasThesis: false }
    const input = buildInput(context)
    expect(input.actionPhase).toBe('thesis')

    const queue = deriveIdentityQueue(input)
    const nextAction = queue.filter((item) => item.kind === 'next-action')
    expect(nextAction).toHaveLength(1)
    expect(nextAction[0]).toMatchObject({
      id: 'next-action:thesis',
      actionId: 'thesis',
      layer: 'thesis',
      priority: 0,
      dismissable: false,
    })
  })

  it('omits the next-action at the terminal review phase', () => {
    const queue = deriveIdentityQueue(buildInput(completeContext))
    expect(queue.some((item) => item.kind === 'next-action')).toBe(false)
  })

  it('maps a stale section to the ladder action that regenerates it', () => {
    // `search` is regenerated by the `strategy` action (the label/section quirk).
    const queue = deriveIdentityQueue(buildInput(completeContext, [], ['positioning', 'search']))
    const stale = queue.filter((item) => item.kind === 'stale')
    expect(stale).toHaveLength(2)
    expect(stale[0]).toMatchObject({ section: 'positioning', actionId: 'positioning', dismissable: false })
    expect(stale[1]).toMatchObject({ section: 'search', actionId: 'strategy' })
    expect(stale[1]?.title).toBe('Refresh search parameters')
  })

  it('marks attention gaps dismissable and preserves their selection', () => {
    const queue = deriveIdentityQueue(
      buildInput(completeContext, [attention({ id: 'fill:thesis' })]),
    )
    const items = queue.filter((item) => item.kind === 'attention')
    expect(items).toHaveLength(1)
    expect(items[0]).toMatchObject({
      id: 'attention:fill:thesis',
      dismissable: true,
      selection: { type: 'thesis' },
    })
  })

  it('orders next-action before stale before attention', () => {
    const context = { ...completeContext, hasThesis: false }
    const queue = deriveIdentityQueue(
      buildInput(context, [attention()], ['positioning']),
    )
    expect(queue.map((item) => item.kind)).toEqual(['next-action', 'stale', 'attention'])
  })
})

describe('deriveIdentityReadiness', () => {
  it('is not research-ready mid-pipeline and reports the next step', () => {
    const context = { ...completeContext, hasPositioning: false }
    const input = buildInput(context)
    const readiness = deriveIdentityReadiness({
      actionPhase: input.actionPhase,
      queue: deriveIdentityQueue(input),
    })
    expect(readiness.researchReady).toBe(false)
    expect(readiness.nextStep).toBe('positioning')
  })

  it('is research-ready at the review phase with no blocking work', () => {
    const input = buildInput(completeContext)
    const readiness = deriveIdentityReadiness({
      actionPhase: input.actionPhase,
      queue: deriveIdentityQueue(input),
    })
    expect(readiness).toEqual({
      researchReady: true,
      nextStep: null,
      refinementCount: 0,
      staleCount: 0,
    })
  })

  it('stays research-ready while counting non-blocking refinements and stale sections', () => {
    const input = buildInput(completeContext, [attention(), attention({ id: 'fill:self' })], [
      'positioning',
    ])
    const readiness = deriveIdentityReadiness({
      actionPhase: input.actionPhase,
      queue: deriveIdentityQueue(input),
    })
    expect(readiness.researchReady).toBe(true)
    expect(readiness.refinementCount).toBe(2)
    expect(readiness.staleCount).toBe(1)
  })
})
