#let data = json.decode(sys.inputs.data)

// === Facet brand palette ====================================
#let brand-blue = rgb("#2d6a96")
#let brand-blue-light = rgb("#5ba4d9")
// 12% alpha matches `--accent-primary-subtle` in src/index.css.
#let brand-blue-tint = rgb(45, 106, 150, 31)

// Canonical Facet wordmark lockup, injected as raw SVG markup by the renderer
// (brand/icons/svg/facet-lockup-on-light.svg). Wordmark glyphs are outlined
// paths, so no Instrument Serif font registration is required.
#let brand-lockup = image.decode(sys.inputs.brandLockup, format: "svg", height: 18pt)

#let text-primary = rgb("#0f172a")
#let text-secondary = rgb("#334155")
#let text-tertiary = rgb("#64748b")
#let border-subtle = rgb("#e2e8f0")

#set document(
  title: data.title,
  author: (data.candidateName,),
)

#set page(
  paper: "us-letter",
  margin: (top: 0.55in, bottom: 0.6in, left: 0.7in, right: 0.7in),
  footer: align(center)[
    #text(size: 7.5pt, fill: text-tertiary, font: "DM Mono", tracking: 0.4pt)[
      Generated by Facet · #link("https://myfacets.cv")[#text(fill: brand-blue)[myfacets.cv]] · #data.generatedAt
    ]
  ],
)

#set text(font: "DM Sans", size: 9.5pt, fill: text-primary)
#set par(leading: 0.55em, justify: false)

// === Header band ============================================
#grid(
  columns: (1fr, auto),
  align: (left + horizon, right + horizon),
  [
    #box(baseline: 5pt, brand-lockup)
    #h(12pt)
    #text(size: 8pt, font: "DM Mono", fill: text-tertiary, tracking: 1.2pt)[RECRUITER CARD]
  ],
  [
    #text(size: 8pt, font: "DM Mono", fill: text-tertiary)[#data.generatedAtShort]
  ],
)

#v(7pt)
#line(length: 100%, stroke: 0.6pt + border-subtle)
#v(16pt)

// === Title block ============================================
#text(
  size: 8pt,
  font: "DM Mono",
  weight: "bold",
  fill: brand-blue,
  tracking: 1.2pt,
)[#upper(data.company)]

#v(3pt)

#text(font: "DM Sans", size: 19pt, weight: "bold", fill: text-primary)[#data.role]

#v(10pt)

// === Candidate row + Match KPI ==============================
#grid(
  columns: (1fr, auto),
  column-gutter: 14pt,
  align: (left + horizon, right + horizon),
  [
    #text(size: 11pt, weight: "medium", fill: text-primary)[#data.candidateName]
    #if data.candidateTitle != "" [
      #linebreak()
      #text(size: 9.5pt, fill: text-secondary)[#data.candidateTitle]
    ]
  ],
  [
    #box(
      stroke: 1pt + brand-blue,
      radius: 4pt,
      inset: (x: 11pt, y: 7pt),
      fill: brand-blue-tint,
    )[
      #text(size: 7.5pt, font: "DM Mono", weight: "bold", fill: text-tertiary, tracking: 1pt)[MATCH ]
      #text(size: 15pt, weight: "bold", fill: brand-blue)[#data.matchScorePct%]
    ]
  ],
)

#v(4pt)
#align(right, text(size: 7pt, fill: text-tertiary, style: "italic")[#data.matchScoreMethodology])

#v(14pt)

// === Section helpers ========================================
#let section-header(title) = {
  text(
    size: 8pt,
    font: "DM Mono",
    weight: "bold",
    fill: text-tertiary,
    tracking: 1.2pt,
  )[#upper(title)]
  v(6pt)
}

// Bullet items often follow a "Label: detail" shape. Bold the label so the
// scannable left edge reads first. Skips obvious URLs and labels that are
// too short or too long to plausibly be section labels.
#let bullet-item-content(item) = {
  let parts = item.split(":")
  let label = if parts.len() > 0 { parts.at(0) } else { "" }
  let is-url = item.starts-with("http") or item.starts-with("ftp") or item.starts-with("mailto:")
  if (
    parts.len() >= 2
      and label.len() >= 2
      and label.len() <= 60
      and not is-url
  ) {
    let rest = parts.slice(1).join(":")
    text(size: 9.5pt, fill: text-primary)[#text(weight: "bold")[#label:]#rest]
  } else {
    text(size: 9.5pt, fill: text-primary)[#item]
  }
}

#let bullet-list(items) = {
  if items.len() == 0 {
    text(size: 9pt, fill: text-tertiary, style: "italic")[—]
  } else {
    for item in items {
      grid(
        columns: (10pt, 1fr),
        align: (top, top),
        text(size: 10pt, fill: brand-blue, weight: "bold")[•],
        bullet-item-content(item),
      )
      v(3pt)
    }
  }
}

#let prose-section(title, body) = {
  if body != none and body != "" {
    section-header(title)
    text(size: 9.5pt, fill: text-primary)[#body]
    v(14pt)
  }
}

#let list-section(title, items) = [
  #section-header(title)
  #bullet-list(items)
]

// === Body ===================================================
#prose-section("Summary", data.summary)
#prose-section("Recruiter hook", data.recruiterHook)
#prose-section("Suggested intro", data.suggestedIntro)

// Two columns, each with its own continuous flow of sections. Using a single
// grid row (rather than three rows of two cells) prevents the right column
// from inheriting whitespace when the corresponding left-column section has
// more bullets — each column simply runs as long as its content needs.
#grid(
  columns: (1fr, 1fr),
  column-gutter: 22pt,
  align: top,
  [
    #list-section("Top reasons", data.topReasons)
    #v(14pt)
    #list-section("Skill highlights", data.skillHighlights)
  ],
  [
    #list-section("Proof points", data.proofPoints)
    #v(14pt)
    #list-section("Likely concerns", data.likelyConcerns)
  ],
)

#v(14pt)
#prose-section("Action / CTA", data.actionCta)
