import type { ProfessionalIdentityV3 } from '../identity/schema'
import { notesText } from '../types/audience'
import type { JDAnalysis } from '../types/jdAnalysis'
import type { MatchAssetScore, MatchGap } from '../types/match'
import type { RecruiterCard } from '../types/recruiter'
import { projectForAudience } from './audienceFilter'

const PROOF_POINT_LIMIT = 5
const TOP_REASONS_LIMIT = 5
const SKILL_LIMIT = 6
const CONCERNS_LIMIT = 4

const MATCH_SCORE_METHODOLOGY =
  'Match % is a weighted blend of requirement coverage, skill match strength, and proof-point relevance. Generated by Facet from the candidate identity profile and job description.'

const formatPercent = (value: number): string => `${Math.round(value * 100)}%`

const summarizeAsset = (asset: MatchAssetScore): string => {
  const source = asset.sourceLabel.trim()
  const text = asset.text.trim()
  return source ? `${source}: ${text}` : text
}

const summarizeGap = (gap: MatchGap): string =>
  [gap.label.trim(), gap.reason.trim()].filter(Boolean).join(': ')

const buildCandidateTitle = (identity: ProfessionalIdentityV3, jdAnalysis: JDAnalysis): string =>
  identity.identity.title?.trim() || jdAnalysis.role.trim() || 'Candidate'

const buildCandidateName = (identity: ProfessionalIdentityV3): string =>
  identity.identity.display_name?.trim() || identity.identity.name.trim()

const takeUnique = (values: string[], limit: number): string[] => {
  const seen = new Set<string>()
  const next: string[] = []

  for (const rawValue of values) {
    const value = rawValue.trim()
    const key = value.toLowerCase()
    if (!value || seen.has(key)) continue
    seen.add(key)
    next.push(value)
    if (next.length >= limit) break
  }

  return next
}

const buildActionCta = (jdAnalysis: JDAnalysis): string => {
  const score = jdAnalysis.fitScore
  const company = jdAnalysis.company.trim() || 'this team'
  if (score >= 0.8) return `Strong fit — recommend forwarding the résumé to ${company}'s hiring manager.`
  if (score >= 0.6) return `Solid match — schedule a screen with ${company} to confirm fit.`
  return `Moderate match — sanity-check the JD's hard requirements before forwarding.`
}

export const createRecruiterCard = ({
  id,
  identity,
  jdAnalysis,
}: {
  id: string
  identity: ProfessionalIdentityV3
  jdAnalysis: JDAnalysis
}): RecruiterCard => {
  const projected = projectForAudience(jdAnalysis, 'recruiter')

  const candidateName = buildCandidateName(identity)
  const candidateTitle = buildCandidateTitle(identity, jdAnalysis)

  const topSkillLabels = takeUnique(
    projected.skillMatches.map((skill) => skill.skillName),
    SKILL_LIMIT,
  )

  const topReasons = takeUnique(
    [
      ...projected.advantages.map((advantage) => advantage.claim),
      ...projected.requirements
        .filter((requirement) => requirement.coverageScore >= 0.65)
        .map(
          (requirement) =>
            `${requirement.label} covered with ${formatPercent(requirement.coverageScore)} confidence`,
        ),
    ],
    TOP_REASONS_LIMIT,
  )

  const proofPoints = takeUnique(
    [...projected.evidenceMapping.topBullets, ...projected.evidenceMapping.topProjects].map(summarizeAsset),
    PROOF_POINT_LIMIT,
  )

  // Post-projection, gaps already only contain entries the audience rules
  // surfaced for the recruiter (high severity by default). No extra
  // severity filter is needed here.
  const likelyConcerns = takeUnique(projected.gaps.map(summarizeGap), CONCERNS_LIMIT)

  const recruiterHook =
    `${candidateName} is a ${candidateTitle} with a ${formatPercent(jdAnalysis.fitScore)} match for ${jdAnalysis.role} at ${jdAnalysis.company}.`

  const suggestedIntro = [
    recruiterHook,
    topSkillLabels.length > 0 ? `Lead with ${topSkillLabels.slice(0, 3).join(', ')}.` : '',
    notesText(projected.strengthsToLead).slice(0, 1).join(''),
  ]
    .filter(Boolean)
    .join(' ')

  return {
    id,
    generatedAt: new Date().toISOString(),
    company: jdAnalysis.company.trim() || 'Target Company',
    role: jdAnalysis.role.trim() || 'Target Role',
    candidateName,
    candidateTitle,
    matchScore: jdAnalysis.fitScore,
    matchScoreMethodology: MATCH_SCORE_METHODOLOGY,
    summary: jdAnalysis.summary.trim(),
    recruiterHook,
    suggestedIntro,
    topReasons,
    proofPoints,
    skillHighlights: topSkillLabels,
    likelyConcerns,
    actionCta: buildActionCta(jdAnalysis),
  }
}
