import type { PipelineEntry } from '../../types/pipeline'

/**
 * Fictional sample data for development and testing.
 * Contains NO real companies, comp ranges, or personal details.
 */
export const samplePipelineJobDescriptions = {
  acme:
    'Acme Corp is hiring a Staff Platform Engineer to lead the next phase of our internal developer platform. You will own Kubernetes delivery workflows, Terraform module strategy, and CI/CD reliability for more than eighty product services. The role partners closely with infrastructure, security, and product engineering teams to reduce deployment friction, improve observability, and define paved-road standards that product teams actually adopt. Strong candidates have operated production platforms, balanced self-service with guardrails, and used metrics to prove improvements in developer velocity and incident reduction.',
  initech:
    'Initech is hiring a Senior Security Engineer to build security automation for a remote-first engineering organization. You will own cloud posture checks, secrets rotation workflows, and CI security controls across AWS, Kubernetes, and GitHub Actions. The team needs an engineer who can turn policy into practical platform capabilities, partner with application teams during design reviews, and write production-quality Python or TypeScript services. Experience with threat modeling, incident response, and infrastructure-as-code guardrails is especially valuable.',
  globex:
    'Globex Corporation is hiring a Developer Productivity Engineer to improve build, test, and release systems across a TypeScript-heavy monorepo. You will modernize CI pipelines, reduce flaky test time, improve local development loops, and build internal tooling that helps hundreds of engineers ship safely. The role requires comfort with distributed build systems, observability for delivery workflows, and pragmatic change management across many teams. Bonus points for Go experience, large-scale package management, and hands-on work with developer experience metrics.',
} as const

export const samplePipelineData: PipelineEntry[] = [
  {
    id: 'pipe-sample-1',
    company: 'Acme Corp',
    role: 'Staff Platform Engineer',
    tier: '1',
    status: 'interviewing',
    comp: '$170K–$210K',
    url: 'https://example.com/jobs/1',
    contact: 'Jane Recruiter',
    vectorId: null,
    jobDescription: samplePipelineJobDescriptions.acme,
    jobDescriptionSourceUrl: 'https://example.com/jobs/1',
    presetId: null,
    resumeVariant: '',
    resumeGeneration: null,
    positioning: 'Platform engineering experience aligns with their infrastructure modernization initiative.',
    skillMatch: 'Python, Terraform, Kubernetes, CI/CD',
    nextStep: 'System design interview scheduled for next week',
    notes: 'Async-first culture. Series C, ~200 employees.',
    appMethod: 'direct-apply',
    response: 'screen-scheduled',
    daysToResponse: 3,
    rounds: 2,
    format: ['hr-screen', 'tech-discussion'],
    rejectionStage: '',
    rejectionReason: '',
    offerAmount: '',
    dateApplied: '2026-02-15',
    dateClosed: '',
    lastAction: '2026-03-01',
    createdAt: '2026-02-10',
    history: [
      { date: '2026-02-10', note: 'Created' },
      { date: '2026-02-15', note: 'Applied via website' },
      { date: '2026-02-18', note: 'Recruiter screen scheduled' },
      { date: '2026-03-01', note: 'Technical discussion completed' },
    ],
  },
  {
    id: 'pipe-sample-2',
    company: 'Initech',
    role: 'Sr Security Engineer',
    tier: '2',
    status: 'applied',
    comp: '$150K–$180K',
    url: 'https://example.com/jobs/2',
    contact: '',
    vectorId: null,
    jobDescription: samplePipelineJobDescriptions.initech,
    jobDescriptionSourceUrl: 'https://example.com/jobs/2',
    presetId: null,
    resumeVariant: '',
    resumeGeneration: null,
    positioning: 'Security tooling and automation background is a strong fit.',
    skillMatch: 'Python, AWS, security automation',
    nextStep: 'Waiting for response',
    notes: 'Remote-first. Building security platform from scratch.',
    appMethod: 'referral',
    response: 'none',
    daysToResponse: null,
    rounds: null,
    format: [],
    rejectionStage: '',
    rejectionReason: '',
    offerAmount: '',
    dateApplied: '2026-03-01',
    dateClosed: '',
    lastAction: '2026-03-01',
    createdAt: '2026-02-28',
    history: [
      { date: '2026-02-28', note: 'Created' },
      { date: '2026-03-01', note: 'Applied via referral' },
    ],
  },
  {
    id: 'pipe-sample-3',
    company: 'Globex Corporation',
    role: 'Developer Productivity Engineer',
    tier: '1',
    status: 'rejected',
    comp: '$180K–$220K',
    url: 'https://example.com/jobs/3',
    contact: 'Bob Hiring',
    vectorId: null,
    jobDescription: samplePipelineJobDescriptions.globex,
    jobDescriptionSourceUrl: 'https://example.com/jobs/3',
    presetId: null,
    resumeVariant: '',
    resumeGeneration: null,
    positioning: 'Build system and CI/CD pipeline expertise matches their needs.',
    skillMatch: 'CI/CD, build systems, TypeScript, monorepo',
    nextStep: '',
    notes: 'Rejected after technical round. Feedback: wanted more Go experience.',
    appMethod: 'direct-apply',
    response: 'human-reject',
    daysToResponse: 5,
    rounds: 3,
    format: ['hr-screen', 'system-design', 'behavioral'],
    rejectionStage: 'technical',
    rejectionReason: 'Wanted more Go experience',
    offerAmount: '',
    dateApplied: '2026-01-20',
    dateClosed: '2026-02-15',
    lastAction: '2026-02-15',
    createdAt: '2026-01-15',
    history: [
      { date: '2026-01-15', note: 'Created' },
      { date: '2026-01-20', note: 'Applied' },
      { date: '2026-01-25', note: 'HR screen' },
      { date: '2026-02-05', note: 'System design round' },
      { date: '2026-02-15', note: 'Rejected — wanted Go experience' },
    ],
  },
]
